### ISSUE TITLE
Fallback to emergency logger on HTTP requests

### ISSUE THREAD

**Issue by lfglopes** [dev-this/laravel-console-logg#8]
If I write `Log::info('test')` on an HTTP controller, the `console-logg` driver is not recognized and I get the following on `laravel.log`:

```
[2022-07-04 15:44:53] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [console-logg] is not defined. at /var/www/html/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:192)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(118): Illuminate\\Log\\LogManager->resolve('console-logg')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(98): Illuminate\\Log\\LogManager->get('console-logg')
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(87): Illuminate\\Log\\LogManager->driver('console-logg')
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(241): Illuminate\\Log\\LogManager->channel('console-logg')
#4 [internal function]: Illuminate\\Log\\LogManager->Illuminate\\Log\\{closure}('console-logg', 1)
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Collection.php(638): array_map(Object(Closure), Array, Array)
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(311): Illuminate\\Support\\Collection->map(Object(Closure))
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(242): Illuminate\\Support\\Collection->flatMap(Object(Closure))
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(202): Illuminate\\Log\\LogManager->createStackDriver(Array)
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(118): Illuminate\\Log\\LogManager->resolve('stack')
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(98): Illuminate\\Log\\LogManager->get('stack')
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(621): Illuminate\\Log\\LogManager->driver()
"} 

(...)
```

**Comment by lfglopes** [comment]
Workaround,

On `config/logging.php` assuming this configuration:

```php
    'channels' => [
        'stack' => [
            'driver' => 'stack',
            'channels' => ['daily', 'console-logg'],
            'ignore_exceptions' => false,
        ],
```

On the top write:

```php
$defaultChannels = ['daily'];
if (in_array(PHP_SAPI, ['cli', 'cli-server', 'phpdbg'])) {
    $defaultChannels[] = 'console-logg';
}
```

And then change the config:

```php
    'channels' => [
        'stack' => [
            'driver' => 'stack',
            'channels' => $defaultChannels, // ['daily', 'console-logg'],
            'ignore_exceptions' => false,
        ],
```

**Comment by VeryStrongFingers** [comment]
I haven't been able to replicate the problem. Will need some more details off you.

- Which version of Laravel?
- How are you running the server when this occurs? (artisan serve? FastCGI? etc)

I'm thinking the issue probably derives from this code https://github.com/dev-this/laravel-console-logg/blob/4873c46a83a2ec3fb18091ab4f5bccef803d8af6/src/Providers/ConsoleLoggServiceProvider.php#L26-L29 - but those further details off you would be good.

**Comment by lfglopes** [comment]
Thanks for the reply.
I'm running Laravel 7.30.6 and the server is running via FastCGI.

**Comment by lfglopes** [comment]
Hello,
I've updated console-logg and `laravel/framework` to version v8.83.18

Now I get the following:

```
[2022-07-13 10:07:53] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (Error(code: 0): Call to undefined method DevThis\\ConsoleLogg\\LogHandlers\\NonConsole::getProcessors() at /var/www/html/vendor/laravel/framework/src/Illuminate/Log/Logger.php:308)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(261): Illuminate\\Log\\Logger->__call('getProcessors', Array)
#1 [internal function]: Illuminate\\Log\\LogManager->Illuminate\\Log\\{closure}('console-logg', 1)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(695): array_map(Object(Closure), Array, Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(354): Illuminate\\Support\\Collection->map(Object(Closure))
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(262): Illuminate\\Support\\Collection->flatMap(Object(Closure))
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(210): Illuminate\\Log\\LogManager->createStackDriver(Array)
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(125): Illuminate\\Log\\LogManager->resolve('stack', Array)
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(112): Illuminate\\Log\\LogManager->get('stack')
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(668): Illuminate\\Log\\LogManager->driver()
```
